### ISSUE TITLE
meta: issue to track binary identical functions

### ISSUE THREAD

**Issue by mewmew** [diasurgical/devil-nightly#59]
The intention of this issue is to provide an overall view of which functions are already made binary identical. Once an entire file becomes binary identical, we can omit the functions in that file and simply state that the file is identical.

The function names below are taken from the [scalpel](https://github.com/diasurgical/scalpel) repo. If you notice any mismatch between the names, then we should update those in the [make_diablo.py](https://github.com/diasurgical/scalpel/blob/master/script/make_diablo.py) script. They are ordered by their occurrence in `Diablo.exe` version 1.09b.

# File summary

- [ ] [appfat.cpp](#appfat.cpp) #62
- [ ] [automap.cpp](#automap.cpp) #63
- [ ] [capture.cpp](#capture.cpp) #64
- [ ] [codec.cpp](#codec.cpp) #65
- [ ] [control.cpp](#control.cpp) #66
- [ ] [cursor.cpp](#cursor.cpp) #67
- [ ] [dead.cpp](#dead.cpp) #68
- [ ] [debug.cpp](#debug.cpp) #69
- [ ] [diablo.cpp](#diablo.cpp) #70
- [x] [doom.cpp](#doom.cpp) #71
- [ ] [drlg_l1.cpp](#drlg_l1.cpp) #72
- [ ] [drlg_l2.cpp](#drlg_l2.cpp) #73
- [ ] [drlg_l3.cpp](#drlg_l3.cpp) #74
- [ ] [drlg_l4.cpp](#drlg_l4.cpp) #75
- [ ] [dthread.cpp](#dthread.cpp) #76
- [ ] [dx.cpp](#dx.cpp) #77
- [ ] [effects.cpp](#effects.cpp) #78
- [ ] [encrypt.cpp](#encrypt.cpp) #79
- [ ] [engine.cpp](#engine.cpp) #80
- [ ] [error.cpp](#error.cpp) #81
- [ ] [fault.cpp](#fault.cpp) #82
- [ ] [gamemenu.cpp](#gamemenu.cpp) #83
- [ ] [gendung.cpp](#gendung.cpp) #84
- [ ] [gmenu.cpp](#gmenu.cpp) #85
- [ ] [help.cpp](#help.cpp) #86
- [ ] [init.cpp](#init.cpp) #87
- [ ] [interfac.cpp](#interfac.cpp) #88
- [ ] [inv.cpp](#inv.cpp) #89
- [ ] [items.cpp](#items.cpp) #90
- [ ] [lighting.cpp](#lighting.cpp) #91
- [ ] [loadsave.cpp](#loadsave.cpp) #92
- [ ] [log.cpp](#log.cpp) #93
- [ ] [mainmenu.cpp](#mainmenu.cpp) #94
- [ ] [minitext.cpp](#minitext.cpp) #95
- [ ] [missiles.cpp](#missiles.cpp) #96
- [ ] [monster.cpp](#monster.cpp) #97
- [ ] [movie.cpp](#movie.cpp) #98
- [ ] [mpqapi.cpp](#mpqapi.cpp) #99
- [ ] [msg.cpp](#msg.cpp) #100
- [ ] [msgcmd.cpp](#msgcmd.cpp) #101
- [ ] [multi.cpp](#multi.cpp) #102
- [ ] [nthread.cpp](#nthread.cpp) #103
- [ ] [objects.cpp](#objects.cpp) #104
- [ ] [pack.cpp](#pack.cpp) #105
- [ ] [palette.cpp](#palette.cpp) #106
- [ ] [path.cpp](#path.cpp) #107
- [ ] [pfile.cpp](#pfile.cpp) #108
- [ ] [player.cpp](#player.cpp) #109
- [ ] [plrmsg.cpp](#plrmsg.cpp) #110
- [ ] [portal.cpp](#portal.cpp) #111
- [ ] [quests.cpp](#quests.cpp) #112
- [ ] [restrict.cpp](#restrict.cpp) #113
- [ ] [scrollrt.cpp](#scrollrt.cpp) #114
- [ ] [setmaps.cpp](#setmaps.cpp) #115
- [ ] [sha1.cpp](#sha1.cpp) #116
- [ ] [sound.cpp](#sound.cpp) #117
- [ ] [spells.cpp](#spells.cpp) #118
- [ ] [stores.cpp](#stores.cpp) #119
- [ ] [sync.cpp](#sync.cpp) #120
- [ ] [themes.cpp](#themes.cpp) #121
- [ ] [tmsg.cpp](#tmsg.cpp) #122
- [ ] [town.cpp](#town.cpp) #123
- [ ] [towners.cpp](#towners.cpp) #124
- [ ] [track.cpp](#track.cpp) #125
- [ ] [trigs.cpp](#trigs.cpp) #126
- [ ] [wave.cpp](#wave.cpp) #127
- [ ] [render.cpp](#render.cpp) #128

**Comment by mewmew** [comment]
@seritools and @AJenbo would you mind filling in the functions you know to be binary identical above?

Cheers,
/u

**Comment by AJenbo** [comment]
I would love to but i don't have the sufficient permissions :(

**Comment by squidcc** [comment]
There are a few functions in pfile.cpp that doesn't match the symbol names in the scripts, I don't know why.
- GetTempLevelNames / pfile_get_temp_level_name
- GetPermLevelNames / pfile_get_perm_level_name
- GetTempSaveNames / pfile_get_temp_name
- GetPermSaveNames is the name used by both, mentioning it just because it obviously fits the pattern
- GetSaveDirectory / pfile_get_archive_path

**Comment by mewmew** [comment]
> I would love to but i don't have the sufficient permissions :(

There should be an easy fix I hope :) @galaxyhaxz do you know how to give permissions to the repo, for editing comments?

**Comment by mewmew** [comment]
> There are a few functions in pfile.cpp that doesn't match the symbol names in the scripts, I don't know why.

Thanks @squidcc! The reason is that the `snake_case` names were taken from the sanctuary repo, while the `CamelCase` names were from the PSX debug info. CamelCase is usually the correct one.

**Comment by mewmew** [comment]
> There should be an easy fix I hope :) @galaxyhaxz do you know how to give permissions to the repo, for editing comments?

Permissions are fixed now :) If anyone else needs access simply ping me.

**Comment by ChaosMarc** [comment]
> Edit: should we split this issue into one per file?

I think this would increase the readability greatly because of the progress label in the ticket search:
![image](https://user-images.githubusercontent.com/1343751/45297469-c63ab400-b505-11e8-8949-5e115b507430.png)

Label all of them with the same label (e.g. binary-exact) so one can easily search for all of them, but keep this ticket also to have a complete progress bar. 

maybe there even is a way to display the progress of all "sub"-tickets in the main ticket's description :)

**Comment by galaxyhaxz** [comment]
> There are a few functions in pfile.cpp that doesn't match the symbol names in the scripts, I don't know why.

Yeah, the project originally used all the names found in the Sanctuary project. Once things were dumped to C many corrections were made to line them up with their original names. In cases where the name is not known or not in the Sanctuary project, `snake_case` was used to make them easier to find so we can eventually correct them.

> The reason is that the snake_case names were taken from the sanctuary repo, while the CamelCase names were from the PSX debug info. CamelCase is usually the correct one.

As a native English speaker I did not know these terms. Thanks for pointing it out.

> Edit: should we split this issue into one per file?

I thought about doing this in the main repo but that might bombard everyone with 70+ notifications and clog the issue section. I think keeping it in one issue is fine, especially since you've listed file names at the top. Perhaps you could change the file name checklist to progress bars and instead each file will have individual checkboxes.

**Comment by galaxyhaxz** [comment]
@mewmew Added a bit of readability, thanks to:
https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f#file-readme-md

**Comment by mewmew** [comment]
> @mewmew Added a bit of readability, thanks to:
https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f#file-readme-md

Great!

@AJenbo pointed out that it takes up to 10 seconds to *tick a box* in the list of functions, probably because it's so long. Have others also noticed this performance issue?

**Comment by mewmew** [comment]
> @mewmew Added a bit of readability, thanks to:
> https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f#file-readme-md

The link anchors seem to have stopped working, but that's probably fine. E.g. click the automap.cpp link https://github.com/diasurgical/devil-nightly/issues/59#automap.cpp does not focus the part of the web page related to automap.cpp. Should we just get rid of the *table of contents* links at the top?

**Comment by AJenbo** [comment]
I'm going to check all the boxes now so hold back on editing for a couple of minutes :)

**Comment by AJenbo** [comment]
List is now updated,

The following where renamed:
DDErrDlg - DDErrMsg
DSErrDlg - DSErrMsg
CenterDlg - center_window
DirErrDlg - DirErrorDlg
palette_save_gamme - SaveGamma
palette_inc_gamma - IncreaseGamma
palette_dec_gamma - DecreaseGamma
palette_update_gamma - UpdateGamma
PM_DoNothing - PM_DoStand

I was unable to find the following on the list:
RedPalette
FreeDebugGFX
unlock_buf_priv
DrawInvMsg
multi_handle_turn_upper_bit
path_get_h_cost
path_pop_active_step
path_new_step
SetPlayerGPtrs

**Comment by AJenbo** [comment]
The diff was done with --no-mem-disp on (same as for the % status generated at each build),
Some additional addresses where also manually ignored (since our data layout isn't identical),
I have ignored jumps between functions (since the size of other functions affect it).

A good deal of functions are nearly identical only failing on signed/unsiged and int/char issues.

Of cause functions may unnoticed diverge again or other silently become identical as we work on the surrounding code and data (galaxy did a big update yesterday that isn't reflected here). But it can be used as a guide for what to work on.

**Comment by mewmew** [comment]
![2018-09-10-185541_376x47_scrot](https://user-images.githubusercontent.com/1414531/45311965-22fc9580-b52b-11e8-96f1-94c1f2da6e75.png)

577 of 2024! What, that's a tremendous start!! Really great work everyone.

**Comment by AJenbo** [comment]
Now we just need some one to time slot it :p 
@mewmew will you take care of adding/renaming/marking the 9 functions i didn't find on the list?

**Comment by mewmew** [comment]
> The following where renamed:
> DDErrDlg - DDErrMsg
> DSErrDlg - DSErrMsg
> CenterDlg - center_window
> DirErrDlg - DirErrorDlg
> palette_save_gamme - SaveGamma
> palette_inc_gamma - IncreaseGamma
> palette_dec_gamma - DecreaseGamma
> palette_update_gamma - UpdateGamma
> PM_DoNothing - PM_DoStand

Fixed in rev https://github.com/diasurgical/scalpel/commit/9e5419a8865d5eb8fbc943774e4cce59276d2d6d.

**Comment by mewmew** [comment]
> @mewmew will you take care of adding/renaming/marking the 9 functions i didn't find on the list?

On it.

**Comment by mewmew** [comment]
Did the following translation:

multi_handle_turn_upper_bit -> multi_wait_delta_send
CaptureRedPal -> RedPalette
FreeDebug -> FreeDebugGFX
dx_unlock_mutex -> unlock_buf_priv
DupeInvMsg -> DrawInvMsg
path_decrease_node -> path_pop_active_step
path_clear_node -> path_new_step
path_xycoord -> path_get_h_cost
player_init_cl2_hdrs -> SetPlayerGPtrs

**Comment by seritools** [comment]
should've just used the function names from the comparer config :^) :P

**Comment by mewmew** [comment]
hehe :p Well, it's better this way in the sense that we fix bugs in the scalpel repo ^^

**Comment by AJenbo** [comment]
@seritools whats the cause for the handfull of functions that the comparer can't find when you run --generate-full?

**Comment by seritools** [comment]
Oh, riivaaja uses the old 0.3.2 release without [these](https://github.com/diasurgical/devilution-comparer/commit/cd853439ca2e59c57c1548e57f543f0d2b0724ff) changes

**Comment by AJenbo** [comment]
Arh, looks like the remaining are just junk functions:
```
WARN: Function '$E2' was not found in the config.
WARN: Function '$E1' was not found in the config.
WARN: Function '__OFSUB__' was not found in the config.
WARN: Function '$E5' was not found in the config.
WARN: Function '$E4' was not found in the config.
WARN: Function '__ROL__' was not found in the config.
WARN: Function '__SETS__' was not found in the config.

```

**Comment by seritools** [comment]
$E<n> are the cpp_init struct initializers, the rest are functions that IDA provides (will be removed while cleaning up)

**Comment by AJenbo** [comment]
Closing this as it has been converted to a milestone and split in to per file issues. I'm thinking this might also be a way for us to assign the person who is mainly working on a specific file to sort of avoid conflicting work.

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devil-nightly/milestone/1

**Comment by sskras** [comment]
Wow, so realtime, much thanks, really! : )

**Comment by sskras** [comment]
Wow, so realtime, many thanks, really! : )

**Comment by mewmew** [comment]
> https://github.com/diasurgical/devil-nightly/milestone/1

That's cool. Also great that each issue has a progress bar.
